// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCwC6AsR9QGDaghO2NM3uG-bCuuElQkkE',
    appId: '1:23300626098:web:27ce49b75a02a07af39bab',
    messagingSenderId: '23300626098',
    projectId: 'flux-698aa',
    authDomain: 'flux-698aa.firebaseapp.com',
    storageBucket: 'flux-698aa.firebasestorage.app',
    measurementId: 'G-HK94J3G7C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJk5cNXl_a2guVleaVH9qlUtI_BVCn81E',
    appId: '1:23300626098:android:6b90a5dd17f1b819f39bab',
    messagingSenderId: '23300626098',
    projectId: 'flux-698aa',
    storageBucket: 'flux-698aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA77a4kJrWf1YN7Mcpzh0PWxrM5jGptGX0',
    appId: '1:23300626098:ios:219f8f6bfa80f1f6f39bab',
    messagingSenderId: '23300626098',
    projectId: 'flux-698aa',
    storageBucket: 'flux-698aa.firebasestorage.app',
    iosBundleId: 'com.example.fluxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA77a4kJrWf1YN7Mcpzh0PWxrM5jGptGX0',
    appId: '1:23300626098:ios:219f8f6bfa80f1f6f39bab',
    messagingSenderId: '23300626098',
    projectId: 'flux-698aa',
    storageBucket: 'flux-698aa.firebasestorage.app',
    iosBundleId: 'com.example.fluxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCwC6AsR9QGDaghO2NM3uG-bCuuElQkkE',
    appId: '1:23300626098:web:99eda728e616f76bf39bab',
    messagingSenderId: '23300626098',
    projectId: 'flux-698aa',
    authDomain: 'flux-698aa.firebaseapp.com',
    storageBucket: 'flux-698aa.firebasestorage.app',
    measurementId: 'G-989QN1TXQ1',
  );
}
